markdown = """
# ⛽ Smart Contract Security Audit Report

---

### Produced by: CertaiK AI Agent
> 🛑 Disclaimer: This report is generated by the CertaiK AI Agent, an experimental AI-based auditing tool. While every effort is made to ensure accuracy, this report should not replace a professional, human audit.

---

## 📝 Audit Summary
- Project Name: {project_name}
- Contract Address: {address}
- Audit Data: {date}
- Auditors: Certaik AI Agent

---

## 🧐 Introduction
{introduction}

---

## 🔍 Audit Scope
{scope}

---

## ⚠️ Severity Level Definitions
- Critical: 🚨 Issues that can lead to contract compromise or significant financial losses.  
- High: 🔴 Severe bugs that may result in major exploits or disruptions.  
- Medium: 🟠 Moderate risks with potential functional or security impacts.  
- Low: 🟢 Minor issues with limited risk or impact.  
- Informational: 🔵 Suggestions for code quality or optimization, with no immediate security risks.

---

## 🛠 Findings

### 🚨 Critical
{findings_critical}

### 🔴 High
{findings_high}

### 🟠 Medium
{findings_medium}

### 🟢 Low
{findings_low}

### 🔵 Informational
{findings_informational}

---

## 🛡 Recommendations
{recommendations}

---

## ✅ Conclusion
{conclusion}
"""
